
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url:  jdbc:mysql:///school?serverTimezone=UTC
    username: root
    password: 123456

  redis:
    #host: 192.168.203.131
    #port: 6379
    password: 123456
    database: 0
    timeout: 10s
    jedis:
      pool:
        max-idle: 50          # 最大空闲连接数
        min-idle: 10          # 最小空闲连接数
        max-wait:  -1s        # 等待可用连接的最大时间，负数为不限制
        max-active: -1        # 最大活跃连接数，负数为不限制
    cluster:
      nodes:
      - 192.168.203.131:6379
      - 192.168.203.131:6380
      - 192.168.203.131:6381
      #哨兵
    sentinel:
      master: mymaster
      nodes: 192.168.203.131:26379
  data:
    mongodb:
      uri: mongodb://192.168.203.131:27017/test

mybatis:
  type-aliases-package: com.cssl.pojo
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    auto-mapping-behavior: FULL
    use-generated-keys: true
server:
  servlet:
    context-path: /demo